### ISSUE TITLE
crash on downloading torrent

### ISSUE THREAD

**Issue by awb99** [Tribler/docker-tribler-prod#1]
I just followed the instruction, and am getting this exception for every torrent I want to download.
I do have enough disk space, so I dont think this applies:
https://github.com/Tribler/tribler/issues/3247

```
Traceback (most recent call last):
  File "/home/tribler/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.KeyError'>: '233a874a68cca03fae8f52dd09ddd2bab5c63e5f'
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1194:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1203:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:825:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/home/tribler/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:487:_task_process_alerts
/home/tribler/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:336:process_alert
]
```

**Comment by synctext** [comment]
What version of Tribler are you using? OS?
We'll try to fix it.

**Comment by awb99** [comment]
I just did a docker pull and used used the docker run -it that you specified in your readme.
Host os is Manjaro / Arch  linux.

**Comment by awb99** [comment]
I guess that the docker-tribler-prod image that I use is outdated, docker images says it is 20 months old:

```
docker images
tribler/docker-tribler-prod         latest              bdf8372a5ae9        20 months ago       791MB
```

**Comment by awb99** [comment]
BTW: For me the reason to go the docker image route is, that with the arch installer tribler would be in an endless loop on starting it. So I figured the safest way to play with tribler is via docker...

**Comment by devos50** [comment]
Thank you for your report. The docker image is not actively maintained and might contain an older version of Tribler, which could explain this bug. We should update our docker image and remove all the dependencies that we do not longer need anymore. I think we should do this before the Tribler 7.3 release.

**Comment by awb99** [comment]
Thank you!

**Comment by devos50** [comment]
@awb99 I updated the `Dockerfile` to run under Ubuntu 18.04 (instead of 16.04) and updated the list of dependencies used. Could you try to build your container again and check whether this error persists? 👍

**Comment by awb99** [comment]
It is working!!! Cool!  I will test it in more detail, to see if all works
or not. But startup is fast and looks good!! MANY THANKS!

Best Regards,
Florian

**Comment by devos50** [comment]
Great! Thanks for your feedback 👍
